[package]
name = "whichkey"
version = "0.1.0"
edition = "2024"

[dependencies]
fltk = "1.4"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
